New implementation
eldario/golang-learn pull request #3
Opened 2020-11-19 21:07 UTC by eldario

Added implementation

2020-11-20 12:19 UTC, korjavin requested changes

2020-11-20 12:19 UTC, korjavin commented on task2/main.go
> +func (data *SortedArray) GetMax() int {
У нас же сортированный массив, зачем его перебирать?

2020-11-20 12:19 UTC, korjavin commented on task2/main_test.go
> +		data := SortedArray{c.array}
Видим нужен конструктор

2020-11-21 19:04 UTC, eldario commented on task2/main.go
> +func (data *SortedArray) GetMax() int {
И правда. Переделал.

2020-11-21 19:06 UTC, eldario commented on task2/main_test.go
> +		data := SortedArray{c.array}
Не совсем понял..

2020-11-22 10:21 UTC, korjavin approved these changes

2020-11-22 10:21 UTC, korjavin commented on task2/main_test.go
> +		data := SortedArray{c.array}
Тот факт что мы можем создать SortedArray с случайным набором данных, заставляет нас  или верить или пересортировывать потом.

Если бы у нас был конструктор New мы могли бы доверять что у нас всегда консистентное состояние.

2020-11-22 21:07 UTC, korjavin approved these changes

2020-11-22 21:07 UTC, korjavin commented on task2/Makefile
> +	go test ./pkg/sorter/sorter_test.go && go test ./pkg/sorter/list_test.go
можно передавать список пакетов вот так 
go test ./pkg/...

2020-11-22 21:07 UTC, korjavin commented on task2/pkg/sorter/sorter.go
> +		fmt.Print(data.array, actual)
fmt наверное тут от отладки остался.

2020-11-24 18:47 UTC, merged

2020-11-25 09:29 UTC, korjavin commented on task2/main.go
> +	"./pkg/list"
Относительные пути - обычно антипаттерн.

2020-11-25 09:29 UTC, korjavin commented on task2/main.go
> +		witList()
Мы уже знаем интерфейсы можем тут орефакторить

2020-11-25 17:37 UTC, eldario commented on task2/main.go
> +	"./pkg/list"
Наконец-то настроил go.mod
Теперь такой параши больше не будет)

2020-11-25 17:37 UTC, eldario commented on task2/main.go
> +		witList()
Сделаю