Added SortedMap
eldario/golang-learn pull request #4
Opened 2020-11-24 22:11 UTC by eldario

Added implementation of SortedMap

2020-11-25 08:22 UTC, korjavin requested changes
Мне это решение показалось сложным в плане цикломатической сложности.

Давай его побенчмаркаем прежде чем изменять.

2020-11-25 17:45 UTC, eldario commented
@korjavin 
#### Benchmarks

```json
BenchmarkInsert-4                4746104               262 ns/op
BenchmarkGetFrequentUses-4      12489802               100 ns/op
```

2020-11-27 05:55 UTC, korjavin reviewed
я ещё посмотрю

2020-11-27 05:55 UTC, korjavin commented on task3/pkg/reader/reader.go
> +	if _, err := strconv.Atoi(word); err == nil {
Это мне кажется тяжелой процелурой

2020-11-27 05:55 UTC, korjavin commented on task3/pkg/simpleMapper/simpleMapper.go
> +	return &SortedMap{words: make(map[string]int), topCount: 8}
8 - подозрительно выглядит

2020-11-27 06:05 UTC, eldario commented on task3/pkg/simpleMapper/simpleMapper.go
> +	return &SortedMap{words: make(map[string]int), topCount: 8}
Debug mode был, убрал дефолт

2020-11-30 07:25 UTC, eldario commented
@korjavin 

```json
ID  Word    Count  Order  
1   like    35     67     
2   told    29     94     
3   looked  39     113    
4   went    62     167    
5   love    32     206    
6   want    29     217    
7   into    29     223    
8   saw     39     269    
9   any     23     467    
10  got     24     517 
```

2020-12-01 11:53 UTC, korjavin approved these changes

2020-12-01 19:11 UTC, merged